In [1]:
%cd /home/druhe/rail1/src/cnf
%load_ext autoreload
%autoreload 2

import os
os.environ['DATAROOT'] = '/home/druhe/datasets'


/home/druhe/rail1/src/cnf


/home/druhe/rail1/src/cnf/.venv/lib/python3.10/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [2]:
import torch

In [8]:
x = torch.randn(3, 2)

In [9]:
d = torch.cdist(x, x)

In [32]:
d_srt = d.sort(dim=1)[0]

In [49]:
w = torch.eye(3)
z = w * d_srt

In [50]:
z

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 1.4128, 0.0000],
        [0.0000, 0.0000, 3.0818]])

In [51]:
(d[:, None, :] - w[:, :, None])

tensor([[[-1.0000,  0.7012,  2.0818],
         [ 0.0000,  1.7012,  3.0818],
         [ 0.0000,  1.7012,  3.0818]],

        [[ 1.7012,  0.0000,  1.4128],
         [ 0.7012, -1.0000,  0.4128],
         [ 1.7012,  0.0000,  1.4128]],

        [[ 3.0818,  1.4128,  0.0000],
         [ 3.0818,  1.4128,  0.0000],
         [ 2.0818,  0.4128, -1.0000]]])

In [52]:
z

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 1.4128, 0.0000],
        [0.0000, 0.0000, 3.0818]])

In [53]:
d

tensor([[0.0000, 1.7012, 3.0818],
        [1.7012, 0.0000, 1.4128],
        [3.0818, 1.4128, 0.0000]])

In [55]:
z[0] - d[0]

tensor([ 0.0000, -1.7012, -3.0818])

In [57]:
d[1]

tensor([1.7012, 0.0000, 1.4128])

In [61]:
z[1]

tensor([0.0000, 1.4128, 0.0000])

In [62]:
d[1]

tensor([1.7012, 0.0000, 1.4128])

In [79]:
z[1][:, None] * d[1][None]

tensor([[0.0000, 0.0000, 0.0000],
        [2.4034, 0.0000, 1.9961],
        [0.0000, 0.0000, 0.0000]])

In [84]:
A = torch.sigmoid(100 * (z[1][:, None] - d[1][None])) * z[1][:, None] * d[1][None]

In [90]:
A

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [7.2098e-13, 0.0000e+00, 9.9803e-01],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])